### ISSUE TITLE
What version of the SDK is used? What version of VS?

### ISSUE THREAD

**Issue by dreamwraith** [hypfvieh/foo_subsonic#1]
I can't get this to build, I get the following error when attempting to build on Win10 VS2k15 Community:

Severity    Code    Description Project File    Line
Error   C1083   Cannot open include file: 'atlapp.h': No such file or directory foo_subsonic    c:\users\diabolicallyrandom\source\repos\foo_sdk\foobar2000\ATLHelpers\ATLHelpers.h 9

Additionally, the solution shows a "wtl" vcproject that is missing. Nothing for WTL is mentioned in the install req, and nothing 

Can you share more information on your build environment? Thanks.

**Comment by hypfvieh** [comment]
Sorry, I forget to mention that WTL is also required.
atlapp.h is part of WTL.

I updated the README at that point, sorry again :(

Also I used SDK 2015-01-14, but usually it should also work with newer SDK versions.

**Comment by dreamwraith** [comment]
Thanks for the update - so this is probably me being dense - I have never worked with or used WTL before - but the solution for the component is looking for a vcxproj file for WTL itself, but I don't see one in source, and I don't see one in the source download for WTL either - at least not one named "wtl.vcxproj" - any thoughts on what I might be missing? 

Thanks!

**Comment by hypfvieh** [comment]
You have to create the project yourself.
Just create a new VS-Project and add all files from the Include directory of WTL to it (as header files).
