### ISSUE TITLE
Keep database + Integration with Music Library

### ISSUE THREAD

**Issue by alfureu** [hypfvieh/foo_subsonic#2]
I was wondering, whether there is any way how to avoid keep refreshing the catalog manually and whenever one opens foobar2000 have the catalog just ready from the previous refresh. Currently, every time I close+reopen the app I need to manually refresh the catalog which takes time and is heavy on resources on server-side...

Also, maybe incorporating the subsonic songs into the Music Library might be something to consider as enhancement...

**Comment by hypfvieh** [comment]
It usually keeps the retrieved catalog (this is what sqliteCacheDb is for). Maybe there is something wrong with permissions or something else is broken. 

I wrote this plugin 4 years ago and I don't use it anymore, so I don't know if it is still working with newer windows/foobar versions. 
Maybe you try the fork at [jives repo](https://github.com/jives/foo_subsonic). He already did some improvements regarding subsonic API and SSL/TLS on windows 7

**Comment by alfureu** [comment]
Thanks, testing. Out of curiosity, may I ask what are you using nowadays? I guess you did not give up your subsonic library...

**Comment by hypfvieh** [comment]
I have to admit that I'm not using foobar (or media players at all) much nowadays. 
If I want to listen to music, I use the webinterface of my ampache server.

I really liked foobar and still have it installed on my windows machine, but most of the time I'm running linux (windows is only for gaming, and when I'm gaming I'm not listening to music).

**Comment by alfureu** [comment]
Thanks for sharing this! Much appreciated
